### ISSUE TITLE
Missing comments/javadocs

### ISSUE THREAD

**Issue by tiwanari** [PileProject/drive#24]
Please add comments/javadocs and then check files.
- [ ] ./androidTest/java/com/pileproject/drive/ApplicationTest.java
- [ ] ./main/java/com/pileproject/drive/app/DriveApplication.java
- [ ] ./main/java/com/pileproject/drive/comm/BluetoothCommunicator.java
- [ ] ./main/java/com/pileproject/drive/database/DriveDatabase.java
- [ ] ./main/java/com/pileproject/drive/database/ProgramDataManager.java
- [ ] ./main/java/com/pileproject/drive/database/ProgramDataSpec.java
- [ ] ./main/java/com/pileproject/drive/database/ProgramSpec.java
- [ ] ./main/java/com/pileproject/drive/execution/ExecutionActivityBase.java
- [ ] ./main/java/com/pileproject/drive/execution/ExecutionCondition.java
- [ ] ./main/java/com/pileproject/drive/execution/ExecutionThread.java
- [ ] ./main/java/com/pileproject/drive/execution/MachineController.java
- [ ] ./main/java/com/pileproject/drive/preferences/CommonPreferencesSchema.java
- [ ] ./main/java/com/pileproject/drive/programming/visual/activity/BlockIconAdapter.java
- [ ] ./main/java/com/pileproject/drive/programming/visual/activity/BlockListActivityBase.java
- [ ] ./main/java/com/pileproject/drive/programming/visual/activity/BlockPositionComparator.java
- [ ] ./main/java/com/pileproject/drive/programming/visual/activity/ProgramListFragment.java
- [ ] ./main/java/com/pileproject/drive/programming/visual/activity/ProgrammingActivityBase.java
- [ ] ./main/java/com/pileproject/drive/programming/visual/block/BlockBase.java
- [ ] ./main/java/com/pileproject/drive/programming/visual/block/BlockFactory.java
- [ ] ./main/java/com/pileproject/drive/programming/visual/block/NumTextHolder.java
- [ ] ./main/java/com/pileproject/drive/programming/visual/block/repetition/RepetitionBlock.java
- [ ] ./main/java/com/pileproject/drive/programming/visual/block/repetition/RepetitionBreakBlock.java
- [ ] ./main/java/com/pileproject/drive/programming/visual/block/repetition/RepetitionEndBlock.java
- [ ] ./main/java/com/pileproject/drive/programming/visual/block/repetition/RepetitionHasNumText.java
- [ ] ./main/java/com/pileproject/drive/programming/visual/block/repetition/WhileForeverBlock.java
- [ ] ./main/java/com/pileproject/drive/programming/visual/block/repetition/WhileNumBlock.java
- [ ] ./main/java/com/pileproject/drive/programming/visual/block/selection/SelectionBlock.java
- [ ] ./main/java/com/pileproject/drive/programming/visual/block/selection/SelectionEndBlock.java
- [ ] ./main/java/com/pileproject/drive/programming/visual/block/selection/SelectionHasNumText.java
- [ ] ./main/java/com/pileproject/drive/programming/visual/block/sequence/SequenceBlock.java
- [ ] ./main/java/com/pileproject/drive/programming/visual/block/sequence/SequenceBlockHasNumText.java
- [ ] ./main/java/com/pileproject/drive/programming/visual/layout/BlockSpaceLayout.java
- [ ] ./main/java/com/pileproject/drive/programming/visual/layout/BlockSpaceManager.java
- [ ] ./main/java/com/pileproject/drive/programming/visual/layout/ProgrammingSpaceManager.java
- [ ] ./main/java/com/pileproject/drive/programming/visual/layout/ProgressSpaceManager.java
- [ ] ./main/java/com/pileproject/drive/setting/AppCompatPreferenceActivity.java
- [ ] ./main/java/com/pileproject/drive/setting/SettingActivity.java
- [ ] ./main/java/com/pileproject/drive/setting/app/ProgramData.java
- [ ] ./main/java/com/pileproject/drive/setting/app/ProgramDataAdapter.java
- [ ] ./main/java/com/pileproject/drive/setting/app/ProgramListFragment.java
- [ ] ./main/java/com/pileproject/drive/setting/app/SupervisorModeFragment.java
- [ ] ./main/java/com/pileproject/drive/setting/machine/DeviceListAdapter.java
- [ ] ./main/java/com/pileproject/drive/setting/machine/DeviceListItemView.java
- [ ] ./main/java/com/pileproject/drive/setting/machine/DeviceSelectFragment.java
- [ ] ./main/java/com/pileproject/drive/title/TitleActivityBase.java
- [ ] ./main/java/com/pileproject/drive/util/DeployUtils.java
- [ ] ./main/java/com/pileproject/drive/util/MeasurementUnit.java
- [ ] ./main/java/com/pileproject/drive/util/Range.java
- [ ] ./main/java/com/pileproject/drive/util/Unit.java
- [ ] ./main/java/com/pileproject/drive/view/FrameView.java
- [ ] ./main/java/com/pileproject/drive/view/NumberSelectSeekBarView.java
- [ ] ./main/java/com/pileproject/drive/view/NumberSelectView.java
- [ ] ./main/java/com/pileproject/drive/view/NumberSelectWheelScrollerView.java
- [ ] ./main/java/com/pileproject/drive/view/PortTextView.java
- [ ] ./nxt/java/com/pileproject/drive/execution/NxtController.java
- [ ] ./nxt/java/com/pileproject/drive/execution/NxtExecutionActivity.java
- [ ] ./nxt/java/com/pileproject/drive/preferences/BlockPreferencesSchema.java
- [ ] ./nxt/java/com/pileproject/drive/preferences/MachinePreferencesSchema.java
- [ ] ./nxt/java/com/pileproject/drive/programming/visual/activity/NxtBlockListActivity.java
- [ ] ./nxt/java/com/pileproject/drive/programming/visual/activity/NxtProgrammingActivity.java
- [ ] ./nxt/java/com/pileproject/drive/programming/visual/block/selection/IfNxtIsOutOfLineBlock.java
- [ ] ./nxt/java/com/pileproject/drive/programming/visual/block/selection/IfNxtWasTouchedBlock.java
- [ ] ./nxt/java/com/pileproject/drive/programming/visual/block/selection/IfThereWasALargeSoundBlock.java
- [ ] ./nxt/java/com/pileproject/drive/programming/visual/block/sequence/BackwardSecBlock.java
- [ ] ./nxt/java/com/pileproject/drive/programming/visual/block/sequence/ForwardSecBlock.java
- [ ] ./nxt/java/com/pileproject/drive/programming/visual/block/sequence/SetLeftMotorSpeedBlock.java
- [ ] ./nxt/java/com/pileproject/drive/programming/visual/block/sequence/SetRightMotorSpeedBlock.java
- [ ] ./nxt/java/com/pileproject/drive/programming/visual/block/sequence/StopSecBlock.java
- [ ] ./nxt/java/com/pileproject/drive/programming/visual/block/sequence/TurnLeftSecBlock.java
- [ ] ./nxt/java/com/pileproject/drive/programming/visual/block/sequence/TurnRightSecBlock.java
- [ ] ./nxt/java/com/pileproject/drive/setting/NxtSettingActivity.java
- [ ] ./nxt/java/com/pileproject/drive/setting/machine/NxtPortConnectionFragment.java
- [ ] ./nxt/java/com/pileproject/drive/setting/machine/NxtThresholdFragment.java
- [ ] ./nxt/java/com/pileproject/drive/title/NxtTitleActivity.java
- [ ] ./nxt/java/com/pileproject/drive/view/NxtMotorPortTextView.java
- [ ] ./nxt/java/com/pileproject/drive/view/NxtSensorPortTextView.java

**Comment by mandaiy** [comment]
I believe that we should discuss the format, the graininess, and the targets of the comment in advance.
e.g., I do not know whether I should start the comment with capital letters or not, I should comment on private methods or not.

**Comment by tiwanari** [comment]
Yeah, you are right. Actually, they are what I'm confusing in refactoring. 

Let me show some suggestions here:
- comments (not javadocs) should be started with lower case because capital cases in codes look somewhat noisy for me.
- you don't have to add javadocs on private methods because they can not be referred from other sources.

And, I want to discuss:
- how about starts javadocs with upper case? I think it is natural that they become multiple lines and capital letters are easy to read for the situation.
- the format of javadocs like @params, @returns, and so on.

Let's start discussing here for others and please tell me your concerns about them.

**Comment by mandaiy** [comment]
> how about starts javadocs with upper case? I think it is natural that they become multiple lines and capital letters are easy to read for the situation.

I agree this since they are 'docs'. I also believe we should write the docs as sentence.

> the format of javadocs like @params, @returns, and so on.

Do we need @author and @version?
I think they are not necessary because we cannot specify the author and version in our development style.
In my humble opinion, the @exception tags are mandatory if throws.
And the @param and @return are nice but I don't think they should always be noted, since sometimes
they provide no information.

http://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html#CHDJGIJB

**Comment by tiwanari** [comment]
I totally agree with you. 

Let me sum up them:
- javadocs should start with capital letters so that they are documents
- remove @author and @version
- add @exception if a method can meet such case
- keep @param and @return if they are strongly necessary

Is there any concern?

**Comment by mandaiy** [comment]
There are no other concerns. Thank you :)

**Comment by tiwanari** [comment]
#62 solved this.
