### ISSUE TITLE
NxtControllerBuilder の必要性と実装

### ISSUE THREAD

**Issue by tiwanari** [PileProject/drive#3]
あってもよいが，特別必要ではない
現在の ControllerBuilder では，接続されていないものは null が入っているが，
値を取得しようとすると null pointer exception で落ちるので何かしらの対処が必要
（Userの問題ではないので例外終了はおかしい）．

**Comment by tiwanari** [comment]
Builder は削除したけど動作確認が不十分

**Comment by makotoshimazu** [comment]
Could you rewrite this in English?

**Comment by tiwanari** [comment]
Sorry for that but this can be checked easily by using an NXT, and I'll do that shortly (I was too lazy to do that 🙇 ). If there is a problem, I will take it as a new issue.

**Comment by tiwanari** [comment]
As I mentioned in #46, this issue was solved. Thanks.
